kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart_version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    nauta_app_name: jupyter
spec:
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    runName: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888