# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Resource settings
resources:
  requests:
    cpu: 2
    memory: 8000000000
    gpu: 1
  limits:
    cpu: 2
    memory: 8000000000
    gpu: 1

# nodeSelector
nodeSelector:
  gpu: "True"

# Shorthands for setting both limits and requests of cpu/memory
cpu: null
memory: null
gpu: 1

# Settings for CLI automatic resource configuration
cpu_fraction: 0.5
memory_fraction: 0.5

# Settings below  are not intended to be changed
JupyterPort: 8888
image:
  pullPolicy: IfNotPresent
  clusterRepository: {{ NAUTA.ExperimentImage }}

service:
  type: ClusterIP
experimentName:  {{ NAUTA.ExperimentName }} 
podCount: 1